### PR TITLE
Hristova/fw tpg to ds interface

### LINKED ISSUE #14: Integrate FW TP publishing
This task is just to implement FW TP publishing, based on the FW TP readout type tagged in fdreadoutlibs v1.2.0.

There is already PR #11

### PR DESCRIPTION
**Pull request by hristovaivana**
This is the second PR for the firmware TP integration which concerns the stitched TPs and the interface to DS. 
It is similar to the software TPG interface and re-uses the common parts with the swTGP.   
It corresponds to task https://github.com/DUNE-DAQ/daq-deliverables/issues/20

It is open for review in case someone finds major problems. At the moment the configuration for running the fwTPG is 
missing from this branch. For testing the configuration below was used but it is not part of the automatic configuration generation yet . 
I will work now on the configuration generation in the readout package, but if someone can do it faster this is also fine. However, the channel mapping is also missing and will be added asap.

To run the fwTPG we need the DataLinkHandler to be configured as (similar to the swTPG):
```               {
                    "data": {
                        "qinfos": [
                            {
                                "dir": "input",
                                "inst": "raw_tp_link_0",
                                "name": "raw_input"
                            },
                            {
                                "dir": "output",
                                "inst": "time_sync_q",
                                "name": "timesync"
                            },
                            {
                                "dir": "input",
                                "inst": "raw_tp_data_requests_0",
                                "name": "data_requests_1"
                            },
                            {
                                "dir": "output",
                                "inst": "data_fragments_q",
                                "name": "fragment_queue"
                            },
                            {
                                "dir": "output",
                                "inst": "sw_tp_queue_0",
                                "name": "tp_out"
                            },
                            {
                                "dir": "output",
                                "inst": "tpset_link_0",
                                "name": "tpset_out"
                            },
                            {
                                "dir": "output",
                                "inst": "errored_frames_q",
                                "name": "errored_frames"
                            }
                       ]
                    },
                    "inst": "raw_tp_handler_0",
                    "plugin": "DataLinkHandler"
                },
```

P.S. This is the existing configuration WITHOUT the fwTPG for reference:
```                {
                    "data": {
                        "qinfos": [
                            {
                                "dir": "input",
                                "inst": "raw_tp_link_0",
                                "name": "raw_input"
                            },
                            {
                                "dir": "output",
                                "inst": "time_sync_q",
                                "name": "timesync"
                            },
                            {
                                "dir": "input",
                                "inst": "raw_tp_data_requests_0",
                                "name": "data_requests_1"
                            },
                            {
                                "dir": "output",
                                "inst": "data_fragments_q",
                                "name": "fragment_queue"
                            }
                        ]
                    },
                   "inst": "raw_tp_handler_0",
                    "plugin": "DataLinkHandler"
                },
```

### CODE REVIEW

**Comment by hristovaivana** [comment]
Reioen PR.

**Comment by hristovaivana** [comment]
Reopen.

**Comment by hristovaivana** [comment]
@jimbrooke I have updated this PR for the next review.
I noticed that the github checks were failing because the request to develop is no longer valid, 
this will be a patch to v2.11.0.

**Comment by jimbrooke** [comment]
Thanks @hristovaivana.  So we need to update this PR (or make a new one) that includes the IOManager changes, which are all now merged to develop.  I suggest you also keep a 2.11 compatible branch, but there is no plan to patch 2.11, so no need for a 2.11 PR.

I am happy to start reviewing the code on the 2.11 branch - but you will need to tell me which parts you think are ready for review.

**Comment by hristovaivana** [comment]
At the Preparations for v3.0.0 meeting it was reported that this PR is no longer relevant for v3.0.0.

**Pull request closed without merging**
