### PR TITLE
Aabedabu/perf evaluation testing

### PR DESCRIPTION
**Pull request by adam-abed-abud**
Fix for issue #109 

Tested on `np04-srv-028`, `np04-srv-026` and `np02-srv-002`

### CODE REVIEW

**Comment by adam-abed-abud** [comment]
This PR needs to be fixed because the number of links (=10) is hardcoded at the moment and this is not ideal for testing.

**Review by glehmannmiotto — COMMENTED** [review]
I think that at least the hardcoded number of links set to 10 should be fixed.

**Review by roland-sipos — APPROVED** [review]
LGTM

**Comment by roland-sipos** [comment]
@adam-abed-abud Please apply @glehmannmiotto 's requested changes on the hardcoded "10".

**Comment by adam-abed-abud** [comment]
Added a fix for the hardcoded number of links.

**Review by glehmannmiotto — APPROVED** [review]
LGTM

**Comment by adam-abed-abud** [comment]
Closing this PR without merging because another PR (#121 ) has been opened

**Pull request closed without merging**
